export default [
    "Other",
    "DPS Neelbad",
    "DPS Rau",
    "DPS Indore",
    "Shishukunj North",
    "Shishukunj South",
    "Choithram",
    "NDPS",
    "Queens College",
    "EHIS Indore",
    "Daly College",
    "The Sanskaar Valley School",
    "SPS Saket Nagar",
    "SPS Gandhi Nagar",
    "SPS Rohit Nagar",
    "SPS Dwarka Dham",
    "SPS Katara Extension",
    "SPS Ratibad",
    "Sage Intl Ayodhya Nagar",
    "Sage Intl Danish Kunj",
    "Billabong",
    "Campion",
    "Jawahar School",
    "International Public School",
    "Bal Bhawan",
    "IES Public School",
    "Army Public School",
    "Bal Bharti",
    "St.Montfort",
    "Iconic School"
]
