export default [
    "Other",
    "Delhi Public School, Neelbad",
    "Delhi Public School, RkPuram",
    "Delhi Public School, Rau",
    "Delhi Public School, Indore",
    "The Sanskaar Valley School",
    "IES Public School",
    "Carmel Convent BHEL",
    "Billabong High",
    "Sagar Public School, Saket Nagar ",
    "Sagar Public School, Gandhi Nagar",
    "Sagar Public School, Rohit Nagar ",
    "Sagar Public School, Katara Hills Ext",
    "Sagar Public School, Dwarka Dham ",
    "Sagar Public School, Ratibad ",
    "Bal Bhawan School ",
    "Bhavan Bharti Public School ",
    "Sharda Vidya Mandir ",
    "St. Joseph’s Convent ",
    "Maharishi Vidya Mandir ",
    "Gyan Ganga International School ",
    "St. Montfort School ",
    "Carmel convent ",
    "St Joseph Co-ed",
    "Campion School, Bhopal",
    "Spring Dales, Pusa"
]